files:
- {destination: /var/www/html, source: files/index.html}
hooks:
  AfterInstall:
  - {location: scripts/sleep.sh}
  - {location: scripts/webserver-start.sh}
  BeforeInstall:
  - {location: scripts/webserver-stop.sh}
  - {location: scripts/delete-old-index.sh}
os: linux
permissions:
- group: apache
  mode: 644
  object: /var/www/html
  owner: apache
  pattern: index.html
  type: [file]
version: 0.0
